name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/gcp-logging-tests/gcp-logging-tests/sa-key.json
    steps:
    
    - name: SHOW KEYFILE
      run: echo "${{ secrets.gcp_credentials }}"
    
    - name: Create KEYFILE
      run: echo "${{ secrets.gcp_credentials }}" >> sa-key.json
    
    - name: SHOW
      run: ls

    - name: SHOW
      run: pwd


    - name: echo GAC
      run: echo $GOOGLE_APPLICATION_CREDENTIALS

    - name: cat GAC
      run: cat $GOOGLE_APPLICATION_CREDENTIALS


    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.gcp_credentials }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info

    - name: gcloud auth
      run: gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
    
    - name: echo GAC
      run: echo $GOOGLE_APPLICATION_CREDENTIALS

    - name: cat GAC
      run: cat $GOOGLE_APPLICATION_CREDENTIALS

      
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/gcp-logging-tests/gcp-logging-tests/gcp-logging-tests/sa-key.json
      
